.catalog:
  version: 1.0
  minimum_rancher_version: v1.1.1
  questions:
  - variable: NUM_ETCD
    description: Desired number of Etcd nodes
    label: Etcd Scale
    required: true
    default: 3
    type: int
  - variable: MAX_HEAP_SIZE
    description: The maximum heap size of the Cassandra JVM
    label: Cassandra Heap Size
    required: true
    default: 2G
    type: string
  - variable: CASS_VOLUME_MOUNT
    description: "Absolute path for a host bind mount or <[a-zA-Z0-9][a-zA-Z0-9_.-]*> for a named volume"
    label: Cassandra Persistence Location
    required: true
    default: cassandra
    type: string
  - variable: ETCD_VOLUME_MOUNT
    description: "Absolute path for a host bind mount or <[a-zA-Z0-9][a-zA-Z0-9_.-]*> for a named volume"
    label: Etcd Persistence Location
    required: true
    default: etcd
    type: string
  - variable: NODE_ARGS
    description: Any other node arguments
    label: Node Arguments
    required: false
    default: "-excludeboards aco,his,qst,trash,wsr"
    type: string
etcd:
  retain_ip: true
  scale: ${NUM_ETCD}
  health_check:
    port: 2378
    request_line: GET /health HTTP/1.0
    interval: 5000
    response_timeout: 3000
    healthy_threshold: 1
    unhealthy_threshold: 2
cassandra:
  health_check:
    port: 9042
    interval: 5000
    response_timeout: 3000
    healthy_threshold: 1
    unhealthy_threshold: 2
# Can we _please_ implement sidekick health checks???
#node:
#  health_check:
#    port: 3333
#    interval: 5000
#    response_timeout: 3000
#    healthy_threshold: 1
#    unhealthy_threshold: 2
#api:
#  health_check:
#    port: 4000
#    interval: 5000
#    response_timeout: 3000
#    healthy_threshold: 1
#    unhealthy_threshold: 2